# This file was generated by GoReleaser. DO NOT EDIT.
cask "cligen" do
  name "cligen"
  desc "CLI for generating Go CLI apps with sane defaults and opinionated release pipelines."
  homepage "https://github.com/twinsnes/cligen"
  version "1.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cligen"

  on_macos do
    on_intel do
      url "https://github.com/TWinsnes/cligen/releases/download/v#{version}/cligen_Darwin_x86_64.tar.gz"
      sha256 "43c90084d28d9df861baae21bf18e8fbf19241f901431117d0dcc2afff6d636f"
    end
    on_arm do
      url "https://github.com/TWinsnes/cligen/releases/download/v#{version}/cligen_Darwin_arm64.tar.gz"
      sha256 "1b72fb52e2c066bd895ed5a34e87c11a1c71ea868716af5f09bef4eda79ffaf2"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/TWinsnes/cligen/releases/download/v#{version}/cligen_Linux_x86_64.tar.gz"
      sha256 "ec50d6e67c50785eda81b0be330bfbf5e5c064203b2a4925876898838caf1b02"
    end
    on_arm do
      url "https://github.com/TWinsnes/cligen/releases/download/v#{version}/cligen_Linux_arm64.tar.gz"
      sha256 "818a0d3c187dda5da79c1859ab29f1ee696c150f6543acee129506d1b4ed8355"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cligen"]
    end
  end

  # No zap stanza required
end
