# This file was generated by GoReleaser. DO NOT EDIT.
cask "cligen" do
  name "cligen"
  desc "CLI for generating Go CLI apps with sane defaults and opinionated release pipelines."
  homepage "https://github.com/twinsnes/cligen"
  version "0.0.7"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cligen"

  on_macos do
    on_intel do
      url "https://github.com/TWinsnes/cligen/releases/download/v#{version}/cligen_Darwin_x86_64.tar.gz"
      sha256 "9299f1a4649f54e8bcc90199e96e3a6a8f6a2053cc446c4503f4cec23af7a20e"
    end
    on_arm do
      url "https://github.com/TWinsnes/cligen/releases/download/v#{version}/cligen_Darwin_arm64.tar.gz"
      sha256 "60ba65dd3ff47e62826f379eeebff0530bf73f814319d9aced86df8df3c0f34e"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/TWinsnes/cligen/releases/download/v#{version}/cligen_Linux_x86_64.tar.gz"
      sha256 "859c7015d51eaad9976187aeca247aa4400521c6eae9a4eb4f94514534840b09"
    end
    on_arm do
      url "https://github.com/TWinsnes/cligen/releases/download/v#{version}/cligen_Linux_arm64.tar.gz"
      sha256 "0dad7286d904fe28390817c5b2edbfb4d17d05ff1e8144c5181355a8a894b89d"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cligen"]
    end
  end

  # No zap stanza required
end
