# This file was generated by GoReleaser. DO NOT EDIT.
cask "cligen" do
  name "cligen"
  desc "CLI for generating Go CLI apps with sane defaults and opinionated release pipelines."
  homepage "https://github.com/twinsnes/cligen"
  version "0.0.10"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cligen"

  on_macos do
    on_intel do
      url "https://github.com/TWinsnes/cligen/releases/download/v#{version}/cligen_Darwin_x86_64.tar.gz"
      sha256 "565b09ebc628a488df96b43a6ca731527f387fbb5e7e028814e5521dc9147eb2"
    end
    on_arm do
      url "https://github.com/TWinsnes/cligen/releases/download/v#{version}/cligen_Darwin_arm64.tar.gz"
      sha256 "31f58ce7e52c98cc2128b607450ffa905875dbb63ef04257081a928cc3a85964"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/TWinsnes/cligen/releases/download/v#{version}/cligen_Linux_x86_64.tar.gz"
      sha256 "b8d4600f32f9fc59e6406174bbb40f8082b976a2f06a3001833d16a94656a67f"
    end
    on_arm do
      url "https://github.com/TWinsnes/cligen/releases/download/v#{version}/cligen_Linux_arm64.tar.gz"
      sha256 "fe687d2680080be525dbad06216ef96663d0f99c27d6a3974d8cf7b6d3da7880"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cligen"]
    end
  end

  # No zap stanza required
end
