# This file was generated by GoReleaser. DO NOT EDIT.
cask "contrib" do
  name "contrib"
  desc "Write a small description of the cli purpose"
  homepage "Add link to CLI homepage, or github repo"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "contrib"

  on_macos do
    on_intel do
      url "https://github.com/TWinsnes/contrib/releases/download/v#{version}/contrib_Darwin_x86_64.tar.gz"
      sha256 "8b592c4b386fe524e03196a62a912173d14547cbd9866b1acd1f3b55a5e164f6"
    end
    on_arm do
      url "https://github.com/TWinsnes/contrib/releases/download/v#{version}/contrib_Darwin_arm64.tar.gz"
      sha256 "172c2cfcedf7f115e94b039b357515bf845ac09f48af139d087f2d0fea3465b7"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/TWinsnes/contrib/releases/download/v#{version}/contrib_Linux_x86_64.tar.gz"
      sha256 "ef794b54e5fc0d8241063c09682519c17e60a0663b28d972977ec03d21f357fd"
    end
    on_arm do
      url "https://github.com/TWinsnes/contrib/releases/download/v#{version}/contrib_Linux_arm64.tar.gz"
      sha256 "fc5ed9f8c82287cec644c5bd4e01fc3c275e680f1bb88d2345fbb2d60988d044"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/contrib"]
    end
  end

  # No zap stanza required
end
